### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by yan-goncalves** [wisekaa03/nestjs-ldap#1]
Hey there! How u doing?
First of all, I'd like thanks you for that lib, great idea mate!

Unfortunately, I had this issue:

    ber = this._modification?.toBer(ber);
                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\Yan\Projetos\pep\dev\backend\node_modules\nestjs-ldap\dist\index.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)

Thanks in advance!

**Comment by yan-goncalves** [comment]
I've updated Node.js and resolved it!
